import type { InsertCatalogProduct } from "../drizzle/schema";

/** O catálogo que já compunha a vitrine passa a ser o registro inicial persistente da loja. */
export const initialCatalogSeed: InsertCatalogProduct[] = [
  { slug: "vestido-aurora", name: "Vestido Aurora", category: "vestidos", priceCents: 38900, imageUrl: "/manus-storage/use-brito-editorial-dress_ae794978.jpg", label: "Novo capítulo", color: "Ferrugem", description: "Fluidez e presença para acompanhar o movimento do dia até a noite.", details: ["Viscose encorpada", "Mangas com volume arquitetônico", "Modelagem midi"], sizes: ["PP", "P", "M", "G"], stock: 12, status: "published", sortOrder: 1 },
  { slug: "blazer-selva", name: "Blazer Selva", category: "alfaiataria", priceCents: 52900, imageUrl: "/manus-storage/use-brito-editorial-jacket_355d7a64.webp", label: "Edição limitada", color: "Cacau", description: "Alfaiataria de ombro suave e caimento decidido, feita para multiplicar combinações.", details: ["Tecido de alfaiataria misto", "Forro acetinado", "Botões forrados"], sizes: ["P", "M", "G"], stock: 8, status: "published", sortOrder: 2 },
  { slug: "conjunto-brisa", name: "Conjunto Brisa", category: "tricos", priceCents: 34900, imageUrl: "/manus-storage/use-brito-editorial-knit_54d2459a.jpeg", label: "Textura da vez", color: "Tijolo", description: "Duas peças, muitas possibilidades: ponto canelado com conforto de presença.", details: ["Malha canelada macia", "Top e saia vendidos juntos", "Elasticidade confortável"], sizes: ["P", "M", "G"], stock: 4, status: "published", sortOrder: 3 },
  { slug: "camisa-linha", name: "Camisa Linha", category: "essenciais", priceCents: 26900, imageUrl: "/manus-storage/use-brito-editorial-portrait_343cf51a.webp", color: "Marfim", description: "Um essencial de toque leve, desenhado para entrar em qualquer composição.", details: ["Algodão com toque macio", "Gola clássica", "Punhos alongados"], sizes: ["PP", "P", "M", "G"], stock: 15, status: "published", sortOrder: 4 },
  { slug: "calca-ritmo", name: "Calça Ritmo", category: "alfaiataria", priceCents: 31900, imageUrl: "/manus-storage/use-brito-editorial-tailoring_132c9646.jpg", color: "Areia", description: "Cintura alta e perna ampla para dar ritmo aos dias que pedem presença.", details: ["Cintura alta", "Pregas frontais", "Barra ampla"], sizes: ["P", "M", "G", "GG"], stock: 6, status: "published", sortOrder: 5 },
  { slug: "regata-orla", name: "Regata Orla", category: "essenciais", priceCents: 14900, imageUrl: "/manus-storage/use-brito-editorial-linen_0ed93893.jpg", label: "Favorito do ateliê", color: "Oliva", description: "Cava precisa, gola delicada e uma tonalidade que conversa com tudo.", details: ["Malha de algodão", "Gola alta suave", "Modelagem próxima ao corpo"], sizes: ["PP", "P", "M", "G"], stock: 17, status: "published", sortOrder: 6 },
  { slug: "saia-vertice", name: "Saia Vértice", category: "vestidos", priceCents: 28900, imageUrl: "/manus-storage/use-brito-hero_a051fd2a.jpg", color: "Cobre", description: "Uma saia de linhas diagonais para transformar a simplicidade em ponto de vista.", details: ["Viscose estruturada", "Fenda lateral", "Fechamento posterior"], sizes: ["P", "M", "G"], stock: 3, status: "published", sortOrder: 7 },
  { slug: "brinco-fagulha", name: "Brinco Fagulha", category: "acessorios", priceCents: 11900, imageUrl: "/manus-storage/use-brito-boutique-rail_d21cbd49.jpg", color: "Metal queimado", description: "Pequeno gesto de metal para iluminar rostos e composições minimalistas.", details: ["Metal com banho dourado", "Leve para uso diário", "Fecho de pino"], sizes: ["Único"], stock: 9, status: "draft", sortOrder: 8 },
];
